### ISSUE TITLE
java.lang.Exception: Too many AI Tasks

### ISSUE THREAD

**Issue by didis54** [ldtteam/Performant#32]
**Describe the bug**
From the Server thread/INFO that is showing in latest.log, it seems to come from an AI of ExtendedMushroom but I don't know if the following error (java.lang.Exception: Too many AI Tasks) is normal or not?

error at:
[15avr.2020 16:04:04.553]
[15avr.2020 16:03:44.158]
[15avr.2020 16:03:14.110]
and lot more...

** Mod version **
extendedmushrooms-1.2.0-1.15.2+.jar
performant-1.15-2.06m.jar
forge-31.1.43

** Logs **
https://gist.github.com/didis54/0ab216901b5c4bf88154c9d915683a43

[15avr.2020 16:01:11.857] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, aborting and pausing
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75776_a(CustomGoalSelector.java:193) ~[?:1.15-2.06m]
	at cech12.extendedmushrooms.ExtendedMushrooms.onLivingSpawn(ExtendedMushrooms.java:135) ~[?:1.2.0-1.15.2+]
	at net.minecraftforge.eventbus.ASMEventHandler_207_ExtendedMushrooms_onLivingSpawn_EnteringChunk.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?]
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:324) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217464_b(ServerWorld.java:657) ~[?:?]
	at net.minecraft.entity.Entity.func_174829_m(Entity.java:784) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_213315_a(LivingEntity.java:3145) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1889) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2289) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1307) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44) ~[?:?]
	at net.minecraft.entity.passive.SheepEntity.func_70636_d(SheepEntity.java:126) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by someaddons** [comment]
take it to exended mushrooms please, they are adding too many AI tasks.

**Comment by someaddons** [comment]
oh forgot to answer the question: No its not normal thats a bug :D

**Comment by didis54** [comment]
Yes that was the question... is the error a bug from Performant because it is trying to remove this entity or it is clearly an error from ExtendedMushrooms, because without Performant this error is not showing at all.

**Comment by someaddons** [comment]
no its clearly an error of the mushroom mod, performant only lets you know when some entity gets waaay too many tasks added from whatever source

**Comment by didis54** [comment]
Ok perfect thanks you from your answer!

**Comment by cech12** [comment]
Thats really weird. I only add one goal at this point. And it is nearly the same as the eat grass goal. I will look at it! :)

**Comment by Raycoms** [comment]
the problem is readding it on every chunk entering and never cleaning them up it seems

**Comment by someaddons** [comment]
ye I saw earlier you add it on chunk enter, instead of world enter
```java
   /**
     * Add eat mushroom goal to sheep entities when configured.
     */
    @SubscribeEvent
    public static void onLivingSpawn(LivingSpawnEvent.EnteringChunk event) {
        if (Config.SHEEP_EAT_MUSHROOM_FROM_GROUND_ENABLED.getValue()) {
            if (event.getEntity() instanceof SheepEntity) { //also mushroom sheep
                SheepEntity sheep = ((SheepEntity) event.getEntity());
                sheep.goalSelector.addGoal(5, new EatMushroomGoal(sheep));
            }
        }
    }
```
use EntityJoinWorldEvent instead

**Comment by cech12** [comment]
Ah ok, thanks a lot!! I will change this :)

**Comment by V-Boy** [comment]
`[13:16:11] [Server thread/WARN] [com.performant.coremod.Performant]: Tried to add over 100 AI tasks, pausing ai and aborting
java.lang.Exception: null
	at com.performant.coremod.entity.ai.CustomGoalSelector.addTask(CustomGoalSelector.java:144) [CustomGoalSelector.class:?]
	at net.daveyx0.primitivemobs.entity.monster.EntitySupportCreeper.TickCentral_TrueOnUpdateTick(EntitySupportCreeper.java:69) [EntitySupportCreeper.class:?]
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56) [TickHub.class:?]
	at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102) [LagGoggles-1.12.2-5.7-130.jar:?]
	at net.daveyx0.primitivemobs.entity.monster.EntitySupportCreeper.onUpdate(EntitySupportCreeper.java) [EntitySupportCreeper.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167) [spongeforge-1.12.2-2838-7.2.1-RC4011.jar:1.12.2-2838-7.2.1-RC4011]
	at net.minecraft.world.WorldServer.redirect$zmd000$onCallEntityUpdate(WorldServer.java:4738) [oo.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1958) [amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1762) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:3928) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`
I keep getting this and this spams my server log, anyway to disable this stuff?

**Comment by someaddons** [comment]
ye tell primitivemobs to fix it, they keep adding new tasks to the mob

**Comment by V-Boy** [comment]
Is there a way to disable the logging entirely? It clogs up my entire server log.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by someaddons** [comment]
no there isnt atm, since its a critical error which would normally completly trash your servers TPS

**Comment by someaddons** [comment]
but I'll add sth with reduces log spam

**Comment by V-Boy** [comment]
I see, but my server tps is doing fine, and the logging itself seems to spam the console and increase the filesize of the log to the point where I rather it not show up at all.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by V-Boy** [comment]
Oh ok, thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
